name: Run this daily

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:       # allows manual run

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
        run: python transfer_daily_tasks.py
